# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


def posts
  [{
    :title        => "Mom Wants To Know If You’ll Be Free If She Visits 14 Months From Now",
    :text         => "JANESVILLE, WI - Expressing her excitement to be shown around where you live and work, your mother reportedly called you Thursday to see if you would be free if she came to visit 14 months from now. “Would the weekend of May 19 work for you?” said your mom of a three-day period in late spring 2017, adding that she needed to know if you had any conflicts on the dates 60 weeks in the future before she booked her ticket. “If you’re busy those days, I’m happy to visit later on—maybe the first week of next June? Whatever works best for you.” Your mother then reportedly informed you that she or your father would be able to pick you up from the airport on Wednesday, November 23 if you come home for Thanksgiving this year."
  },{
    :title        => "Miracle Of Birth Occurs For 83 Billionth Time",
    :text         => "HOPE SPRINGS, AR — The holy and sacrosanct miracle of birth, long revered by human civilization as the most mysterious and magical of all phenomena, took place for what experts are estimating \"must be at least the 83 billionth time\" Tuesday with the successful delivery of eight-pound, four-ounce baby boy Darryl Brandon Severson at Holy Mary Mother Of God Hospital. The milestone was achieved by Carla Severson, 32, an unemployed cosmetology-school graduate and homemaker, and her husband of 14 years, Dwayne Severson, also 32, a former screen-door factory worker and freelance lawncare contractor. Experts say the miracle most likely was the result of the pair engaging in an otherwise routine act of sexual intercourse at some point during late May 1998. The miraculous birth is the couple's fifth."
  },{
    :title        => "Man Makes Quick Call To Parents So Next Week’s Call To Ask For Money Doesn’t Seem That Bad",
    :text         => "NEW YORK — Explaining that he wanted to lay the groundwork with a quick check-in to “see how they were doing,” local 24-year-old Grant Talbot reportedly made a phone call to his parents Friday so his call next week asking for money wouldn’t seem that bad. “Usually, I ask about a few things back home to soften them up before calling back a few days later to say I’m running low on cash,” said Talbot, who told reporters that the 17-minute conversation with his mother and father about topics such as recent family gatherings, kitchen renovations, and plans for the summer would significantly lessen the blow of next week’s request for $350 to help pay bills. “I mentioned a few things going on in my life and hinted that I’m thinking about coming home soon. That should really do the trick so it doesn’t seem like every call is just about money.” At press time, Talbot’s parents had already written out the check to send their son in anticipation of his inevitable follow-up call asking for money."
  },{
    :title        => "Area Man Having One Of His Little Bursts Of Energy Where He Tries To Write A Song",
    :text         => "ATHENS, GA — Humming along Tuesday as he tried out various chord progressions on his acoustic guitar until he found one he liked, local advertising sales representative Daniel Sorenson is, according to sources, currently in the throes of one of his little bursts of creative energy where he attempts to write a song. “Dan’s just in one of his moods where he gets all excited, takes out his guitar, and spends a couple hours trying to come up with a full song,” said Sorenson’s fiancée, Margaret O’Dell, who later added that if Sorenson is feeling particularly energetic, he’ll usually start his song off with some fingerpicking that transitions into vigorous strumming during a chorus. “This happens every couple months or so. He’ll tire himself out in a few hours, right around the time he finishes writing down the lyrics he came up with in this special little notebook he has, or when he tries to put together a bridge.” Sorenson is reportedly expected to awaken tomorrow with a deep sense of inadequacy and shame, and never again revisit the unfinished song."
  },{
    :title        => "Report: Someone Needs To Get Chips And Dip Away From Area Man",
    :text         => "EDISON, NJ — Repeatedly emphasizing that the ruffled potato chips and accompanying French onion dip were just too good, a report released Thursday confirmed that someone needs to get them away from local partygoer Ian Ashcraft before he eats the whole thing. “Seriously, someone better take these things from Ashcraft—he just can’t help himself,” read the report in part, which went on to describe the man, who spent much of the evening standing beside the snack table, as “bad” and “so bad” for continuing to consume the snack after repeatedly stating he should stop. “These things are going to be all gone if somebody doesn’t grab the bowl out of his hand right now. For real, don’t leave them near him, or he might just eat every one of them himself, that’s how good they are. Okay, last one!” The report went on to speculate that the chips and dip must contain crack cocaine."
  },{
    :title        => "Bernie Sanders Clearly In Pocket Of High-Rolling Teacher Who Donated $300 To His Campaign",
    :text         => "BURLINGTON, VT — After accepting a check sent to his campaign office by a local elementary school teacher, presidential candidate Bernie Sanders was roundly criticized Monday as being firmly in the pocket of the high-rolling educator who had donated $300. “He might have the reputation of being the people’s candidate, but when your candidacy is effectively bankrolled by the multi-hundred-dollar donation of a fourth-grade teacher, it’s clear who’s really pulling the strings,” said political analyst Peter Mathews, who noted that when a check arrives with a handwritten note that says “Behind you 100 percent, Bernie!” it comes with certain expectations. “He’s already spouting off talking points about supporting unions and increasing funding for education. Where do you think he got those ideas? He might think he’s not influenced by that money, but when someone has deep enough pockets to drop $300, you pick up the phone when they call.” Mathews went on to say he wouldn’t be surprised if Sanders’ strong support for a living wage could be directly traced to the fat $20 contribution he got from a fast-food worker."
  },{
    :title        => "6-Day Visit To Rural African Village Completely Changes Woman’s Facebook Profile Picture",
    :text         => "ST. LOUIS — Calling the experience “completely transformative,” local 22-year-old Angela Fisher told reporters Tuesday that her six-day visit to the rural Malawian village of Neno has completely changed her profile picture on Facebook. “As soon as I walked into that dusty, remote town and the smiling children started coming up to me, I just knew my Facebook profile photo would change forever,” said Fisher, noting that she realized early in her nearly weeklong visit just how narrow and unworldly her previous Facebook profile photos had been. “I don’t think my profile photo will ever be the same, not after the experience of taking such incredible pictures with my arms around those small African children’s shoulders. Honestly, I can’t even imagine going back to my old Facebook photo of my roommate and I at an outdoor concert.” Since returning, Fisher said she has been encouraging every one of her friends to visit Africa, promising that it would change their Facebook profile photos as well."
  },{
    :title        => "Man Looks On Helplessly As Friend Tells Him Story He’s Already Heard",
    :text         => "OMAHA, NE — Paralyzed with dread as he began to recognize the first few words of his acquaintance’s anecdote, local man Luke Grainger reportedly looked on helplessly Friday as friend Brent McKinnon relayed a story he’d already heard before. “It took me a second or two to realize that Brent had previously told me the story, but by the time I put it together there was nothing I could do to stop him,” said Grainger, who had no choice but to nod along as the several-minutes-long story unfolded in full for a second time. “It was really difficult to keep listening, especially because he used the exact same inflections and made the same pauses for emphasis this time around. I tried hinting that I already knew the story by finishing some of his sentences, but unfortunately it was beyond my control. I couldn’t do anything.” Grainger told reporters he ultimately decided that he might as well sit through the end of the anecdote since he didn’t pay attention the first time."
  },{
    :title        => "Baby Has Sinking Feeling He Left Home Without Oversize Multicolor Plastic Keys",
    :text         => "ROCKFORD, IL — Patting down his onesie with mounting concern, local 8-month-old Joshua McManus was reportedly overcome by a sharp, sinking feeling Monday upon realizing he had left home without his oversize multicolor plastic keys. “Oh, no—you have got to be kidding me,” McManus reportedly thought to himself, his stomach dropping as he wondered how he could possibly make it through the day without his large ring of blue, pink, yellow, and green keys. “Ah, for crying out loud. I got so wrapped up in that game of peekaboo with Dada before I headed out that I must have totally spaced on grabbing them. I bet they’re still sitting there on the activity table right next to my phone-on-wheels. I’m such an idiot.” At press time, a visibly frustrated McManus had vowed to himself that he would never leave the house again without making sure he had picked up his colorful set of keys and explicitly placed them in his mouth."
  },{
    :title        => "Supreme Court Rules Supreme Court Rules",
    :text         => "WASHINGTON - In a landmark decision Monday, the United States Supreme Court ruled 8-1 that it rules. Justice Anthony Kennedy, writing on behalf of the majority, noted that \"while the U.S. Constitution guarantees equality of power among the executive, legislative and judicial branches, it most definitely does not guarantee equality of coolness, and in this regard, the judicial branch kicks that which can be construed as total and complete ass.\""
  },{
    :title        => "Shirtless Biden Washes Trans Am In White House Driveway",
    :text         => "WASHINGTON — Taking advantage of the warm spring weather Monday, Vice President Joe Biden parked his 1981 Trans Am in the White House driveway, removed his undershirt, and spent a leisurely afternoon washing the muscle car and drinking beer. \"This baby just needs a little scrub down,\" said Biden, addressing a tour group as he tucked the sweat-covered top into the belt loop of his cutoff jean shorts. \"Gotta get her looking good so I can impress the chicks when I'm cruising down Pennsylvania [Avenue].\" White House aides said that Biden pulled into the driveway shortly before noon, the chorus of Night Ranger's \"(You Can Still) Rock In America\" blaring from his car's stereo. According to witnesses, Biden spent several minutes maneuvering the Trans Am into the perfect spot, and was observed drumming his fingers on the steering wheel until the song came to a close."
  }]
end

posts.each do |i| Post.create(i) end

Post.all.each do |i|
  date = Post.order(:created_at).first.created_at.to_datetime - (Random.rand(0.5)*10).round
  i.update_attributes created_at: date
end